CreditosApp/Controllers/ClientesController.cs
using CuentasAhorroApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using X.PagedList;

namespace CuentasAhorroApp.Controllers
{
    [TypeFilter(typeof(ExceptionFilter))]
    public class ClientesController : Controller
    {
        public IControlDatosInterface _controlDatosService;
        public ClientesController(IControlDatosInterface controlDatosService)
        {
            _controlDatosService = controlDatosService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAllClientes(int? page, bool Filter, string SearchData)
        {
            IPagedList<Models.Clientes> result = new List<Models.Clientes>().ToPagedList();
            
            var pageNumber = page ?? 1;
            int pageSize = 10;
            var lstClientes = _controlDatosService.GetClientes();
            if (Filter)
            {
                SearchData = SearchData.ToLower();
                result = lstClientes.Where(w => w.Identificador.ToLower().Contains(SearchData) 
                || w.NombreCompleto.ToLower().Contains(SearchData) 
                || w.Telefono.ToLower().Contains(SearchData)
                || w.Email.ToLower().Contains(SearchData))
                    .OrderByDescending(w => w.FechaActualizacion).ToPagedList(pageNumber, pageSize);
            }
            else
            {
                result = lstClientes.OrderByDescending(w => w.FechaActualizacion).ToPagedList(pageNumber, pageSize);
            }

            ViewBag.PageCount = result.PageCount;
            ViewBag.PageNumber = result.PageNumber;
            ViewBag.TotalItemCount = result.TotalItemCount;

            return PartialView("~/Views/Clientes/_ListaClientes.cshtml", result);
        }

        [HttpPost]
        public JsonResult SaveOrUpdateCliente(Models.Clientes data)
        {
            var result = _controlDatosService.CreateCliente(data);
            return Json(result);
        }

        [HttpPost]
        public JsonResult BajaUsuario(int Id)
        {
            var result = _controlDatosService.DeleteCliente(Id);
            return Json(result);
        }

        [HttpGet]
        public JsonResult GetCliente(int Id)
        {
            var result = _controlDatosService.GetCliente(Id);
            return Json(result);
        }
    }
}

CreditosApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppAhorro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
     <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CuentasAhorroApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="overlay" id="generalLoader" style="display: none;">
                <div class="loader" style="display: none;"></div>
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - App Cuentas de Ahorro - <a href="mailto:zohet.d@gmail.com">zohet.d@gmail.com</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/5ed61b48a6.js" crossorigin="anonymous"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
    <script>
        var urlGeneral = '@Url.Content("~/")';
        function cleanModals() {
            $(".cleanText").each(function() {
                $(this).val("");
            });
            $(".cleanNumber").each(function() {
                $(this).val(0);
            });
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>